name: Update Dependencies and Linters
on:
  schedule:
    - cron: '30 8 * * 5'  # Friday 18:00 UTC+9:30
  workflow_dispatch:

jobs:
  refresh-dependencies-and-linters:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      UV_PYTHON: 3.14
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.14"
      - name: Install uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Upgrade dependencies
        run: uv lock --upgrade
      - name: Install prek
        run: uv tool install prek
      - name: Run prek autoupdate
        run: prek autoupdate
      - name: Check for changes in uv.lock or .pre-commit-config.yaml
        id: check_diff
        run: |
          if git diff --quiet uv.lock .pre-commit-config.yaml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Generate token
        if: steps.check_diff.outputs.changed == 'true'
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf
        id: generate-token
        with:
          app-id: ${{ secrets.AUTH_APP_CLIENT_ID }}
          private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
      - name: Create PR with updated dependencies and linters
        if: steps.check_diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore: refresh dependencies and linters"
          title: "chore: refresh dependencies and linters"
          body: |
            This PR updates `uv.lock` by running `uv lock --upgrade`
            and updates `.pre-commit-config.yaml` by running `prek autoupdate`.
            It was triggered automatically (or manually) to keep dependencies and linters up-to-date.
          branch: bot/update-dependencies-and-linters
          author: GitHub Actions <actions@github.com>
          delete-branch: true
